"use client";
import React, { useEffect, useRef, useState } from "react";
import axios from "axios";
import { NavbarOnboarding } from "../../devlinkModified/NavbarOnboarding";
import { DashboardFooter } from "../../devlinkModified/DashboardFooter";

import { OnboardingQuestion2 } from "../../devlinkModified/OnboardingQuestion2";
import { OnboardingQuestion3 } from "../../devlinkModified/OnboardingQuestion3";
import { OnboardingQuestion4 } from "../../devlinkModified/OnboardingQuestion4";
import { OnboardingQuestion5 } from "../../devlinkModified/OnboardingQuestion5";

import { request } from "../../devlinkModified/env";
import { trackPixelEvent } from "../../lib/metaPixel";

import {
  STEPS,
  idx,
  SCRAPE_STEPS,
  JOURNEY_ID,
  STRIPE_PRICE_ID,
  mapToOnboardingPayload,
  scrapeInputs,
  validateForStep,
  errorSwal,
  isAccountExistsError,
  alreadyUnlockedSwal,
} from "./lib";
import { SF } from "./sf-styles";
import { trackOnboardingStage, trackPurchase } from "./track";

import { RelationshipSlide } from "./slides/RelationshipSlide";
import { Story2Slide } from "./slides/Story2Slide";
import { MapSlide } from "./slides/MapSlide";
import { NamesSlide } from "./slides/NamesSlide";
import { BirthdaysSlide } from "./slides/BirthdaysSlide";
import { DataConfirmationStep } from "../onboardingMain/DataConfirmationStep";
import { PersonalSlide } from "./slides/PersonalSlide";
import { GentleQuestionsSlide } from "./slides/GentleQuestionsSlide";
import { QuestionSlide } from "./slides/QuestionSlide";
import { ProgressSlide } from "./slides/ProgressSlide";
import { EmailSlide } from "./slides/EmailSlide";
import { TeaserSlide } from "./slides/TeaserSlide";
import { BuySlide } from "./slides/BuySlide";
import { AfterPurchaseSlide } from "./slides/AfterPurchaseSlide";

import "../styles.css";
import "../swal.css";
import "./signup-flow.css";

const App = () => {
  const [step, setStep] = useState(0);
  const [results, setResults] = useState({});
  const [email, setEmail] = useState("");
  const [checkingOut, setCheckingOut] = useState(false);
  const [teaser, setTeaser] = useState(null);
  const [password, setPassword] = useState("");
  const [settingPassword, setSettingPassword] = useState(false);
  const slideRef = useRef(null);

  const key = STEPS[step];
  const relationshipFocus = results.relationship_focus || "child";
  // relationship_focus === "child" => the user is the parent.
  const isParent = relationshipFocus === "child";

  const scrollTop = () => {
    if (typeof window !== "undefined")
      window.scrollTo({ top: 0, left: 0, behavior: "instant" });
  };

  // Always land at the top of a newly-shown slide. The inline scrollTop() calls
  // in the click handlers fire before React commits the next slide, so on tall
  // pages (e.g. teaser -> buy) the browser would keep the old scroll offset and
  // drop the user near the bottom. Running it in an effect keyed on `step`
  // guarantees the scroll happens *after* the new slide is painted.
  useEffect(() => {
    scrollTop();
  }, [step]);

  // Funnel tracking. Recording on *arrival* rather than on the Next click is
  // deliberate: a click means the stage was left, so click-based tracking never
  // captures the stage someone abandoned — the one worth knowing. Arrival also
  // catches `progress` and `teaser`, which advance on their own with no click.
  // Xano dedupes on (session, flow, stage), so walking backwards is harmless.
  useEffect(() => {
    const flow = results.relationship_focus;
    if (!flow) return;
    // Stage 1 is recorded in goNext instead — see the note there.
    if (step === 0) return;
    // `afterPurchase` is recorded by the Stripe-return effect below instead:
    // that reload wipes `results`, so it has no flow to pass and lets Xano
    // resolve one from this session's earlier stages.
    if (key === "afterPurchase") return;
    trackOnboardingStage(flow, key, step);
  }, [step, key, results.relationship_focus]);

  // Returning from a successful Stripe checkout: fire the Purchase pixel, then
  // send the user to the dashboard where the full deep + summary insight (already
  // generated by submit_onboarding) is viewable. The authToken stored during the
  // email step persists across the Stripe round-trip, so the dashboard can auth.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    const sessionId = params.get("session_id");
    if (!sessionId || sessionId === "{CHECKOUT_SESSION_ID}") return;
    trackPixelEvent("Purchase", {
      value: 21.0,
      currency: "AUD",
      source: "free",
      session_id: sessionId,
    });
    // Record the purchase against the funnel. The flow comes back in the URL
    // that was handed to Stripe before checkout; when it is absent (an older
    // checkout link, or a trimmed URL) Xano falls back to inferring it from
    // this session's earlier stages.
    trackPurchase("afterPurchase", idx("afterPurchase"), params.get("flow"));
    // After a successful payment, go to the password step; setting the password
    // then redirects to the dashboard and auto-opens the reading.
    setStep(idx("afterPurchase"));
  }, []);

  // Clicking "Buy now" sets checkingOut=true and redirects to Stripe. If the
  // user then presses Back, the browser restores this page from its
  // back/forward cache with the stale React state, leaving both buttons stuck
  // on "Redirecting…". `pageshow` fires on that restore (event.persisted), so
  // reset the in-flight flags to make the buttons usable again.
  useEffect(() => {
    const onPageShow = (e) => {
      if (e.persisted) {
        setCheckingOut(false);
        setSettingPassword(false);
      }
    };
    window.addEventListener("pageshow", onPageShow);
    return () => window.removeEventListener("pageshow", onPageShow);
  }, []);

  const goNext = () => {
    let merged = results;
    if (SCRAPE_STEPS.has(key)) {
      merged = { ...results, ...scrapeInputs(slideRef.current) };
      const focus = merged.relationship_focus || "child";
      const err = validateForStep(key, merged, focus === "child");
      if (err) return void errorSwal(err);
      setResults(merged);
    }
    // Count the visitor against the onboarding they committed to. Deliberately
    // here rather than on the radio's change event: picking an option you never
    // confirm isn't entering that flow, and this runs only after validation has
    // passed, so a rejected step never counts.
    // Stage 1 is the one stage that cannot be recorded on arrival: until this
    // slide is answered there is no flow to attribute the visit to. Every later
    // stage is recorded by the effect above, on arrival.
    if (key === "relationship") {
      trackOnboardingStage(merged.relationship_focus, key, step);
    }
    setStep((s) => Math.min(STEPS.length - 1, s + 1));
    scrollTop();
    // console.log(`Results after step ${key}:`, results);
  };

  const goBack = () => {
    setStep((s) => Math.max(0, s - 1));
    scrollTop();
  };

  /* ----- Email slide: register → create record → submit onboarding ----- */
  // Kicks off the API chain in the background and immediately shows the animated
  // progress slide. The progress bars run while the request is in flight; the
  // final bar holds at 80% until `teaser` is set (ready), then completes and the
  // ProgressSlide's onComplete advances to the teaser.
  const submitAndFetchTeaser = async () => {
    const trimmedEmail = email.trim();
    if (!trimmedEmail || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(trimmedEmail)) {
      return errorSwal("Please enter a valid email address");
    }

    setTeaser(null); // reset readiness in case of a retry
    setStep(idx("progress"));
    scrollTop();
    try {

      const mapped = mapToOnboardingPayload(results);

      // 1. Passwordless registration -> auth token
      const reg = await request({
        method: "POST",
        endpoint: "register_passwordless",
        body: { email: trimmedEmail, name : mapped.username || ""},
      });
      const token = reg?.authToken || reg?.token || reg?.auth_token;
      if (!token) throw { message: "We couldn't create your account. Please try again." };
      localStorage.setItem("authToken", token);
      localStorage.setItem("email", trimmedEmail);

      // Persist a minimal user so the navbar + dashboard reflect a logged-in
      // state. The account is created passwordless here; setting a password is a
      // later step. (useStoredUser treats a non-empty object as "logged in".)
      localStorage.setItem(
        "user",
        JSON.stringify({ name: mapped.username || reg?.user?.name || "", email: trimmedEmail })
      );
      window.dispatchEvent(new Event("auth:user-changed"));



      // 2. Create the child / parent record
      const childRes = await request({
        method: "POST",
        endpoint: "add_children",
        headers: { Authorization: `Bearer ${token}` },
        body: {
          name: mapped.childname,
          relationship_focus: relationshipFocus, // "child" | "parent"
          dob: mapped.child_dob,
          place_of_birth: results["child"] || null,
          place_of_birth_id: mapped.child_birth_place_id || null,
          pronoun: mapped.childPronouns || null,
        },
      });
      const child_id = childRes?.child_id || childRes?.id;
      if (!child_id) throw { message: "We couldn't save your details. Please try again." };

      // 3. Submit onboarding -> teaser
      const userRelation = relationshipFocus === "child" ? "parent" : "child";
      const subRes = await request({
        method: "POST",
        endpoint: "submit_onboarding",
        headers: { Authorization: `Bearer ${token}` },
        body: {
          child_id,
          journey_id: JOURNEY_ID,
          onboarding_payload: mapped,
          user_relation: userRelation,
        },
      });

      // console.log(`Submit onboarding response:`, subRes); 

      const teaserText = subRes?.teaser || "";

      // 4. Send the teaser email 
      if(!!teaserText) {
        
        const send_teaser = await axios.post(`/api/send-teaser`, { 
          email: trimmedEmail,
          teaser_text: teaserText,
          parent_name: userRelation === "parent" ? (mapped.username || "") : (mapped.childname || ""),
          child_name: userRelation === "child" ? (mapped.username || "") : (mapped.childname || ""),          
        },{
          headers: {
            'Content-Type': 'application/json',
        }});
      } 

      if (!teaserText) {
        throw {
          message:
            "We couldn't generate your insight just now. Please try again in a moment.",
        };
      }

      // Remember which child to open on the dashboard after purchase. The deep +
      // summary were already generated by submit_onboarding and saved to this
      // child; the dashboard reads them via /get_children using the authToken.
      localStorage.setItem("selectedChild", child_id);

      // Mark ready — the progress slide finishes its last bar and then advances
      // to the teaser via onComplete. (No setStep here.)
      setTeaser({
        teaser: teaserText,
        child_id,
      });
    } catch (e) {
      // Already-registered email: they've already claimed their free insight.
      // Show a warm message and send them to the login page on OK.
      if (isAccountExistsError(e)) {
        setStep(idx("email"));
        scrollTop();
        await alreadyUnlockedSwal();
        window.location.href = "/signin";
        return;
      }
      errorSwal(e?.message);
      // On failure, return to the email slide so the user can retry.
      setStep(idx("email"));
      scrollTop();
    }
  };

  /* ----- Buy slide: Stripe checkout ----- */
  // On a successful payment Stripe returns to success_url; the session_id effect
  // above then advances to the `afterPurchase` (password) step, which sets the
  // password and redirects to the dashboard with the reading auto-opened.
  const startCheckout = async () => {
    setCheckingOut(true);
    try {
      trackPixelEvent("InitiateCheckout", { source: "free" });
      const { url } = await request({
        method: "POST",
        endpoint: "create_checkout_session",
        headers: { Authorization: `Bearer ${localStorage.getItem("authToken")}` },
        body: {
          client_reference_id: localStorage.getItem("selectedChild") || undefined,
          // `flow` rides along to the return page. Stripe echoes success_url
          // back untouched, so the funnel this purchase belongs to is known for
          // certain on return rather than inferred from earlier rows — which
          // misattributes anyone who switched flows partway through.
          success_url: `${window.location.origin}/signup-flow?session_id={CHECKOUT_SESSION_ID}&flow=${relationshipFocus}`,
          cancel_url: `${window.location.origin}/signup-flow?payment_failed`,
          line_items: [{ price: STRIPE_PRICE_ID, quantity: 1 }],
          send_email: true,
        },
      });
      if (!url) throw { message: "Could not start checkout. Please try again." };
      window.location.href = url;
    } catch (e) {
      errorSwal(e?.message);
      setCheckingOut(false);
    }
  };

  /* ----- Password step: set password -> dashboard (auto-open the reading) ----- */
  const submitPassword = async () => {
    const pw = password.trim();
    if (pw.length < 8) {
      return errorSwal("Please choose a password of at least 8 characters");
    }
    setSettingPassword(true);
    try {
      const email = localStorage.getItem("email");
      await request({
        method: "POST",
        endpoint: "update_password",
        headers: { Authorization: `Bearer ${localStorage.getItem("authToken")}` },
        body: { email, newPassword: pw },
      });

      // Re-authenticate with the new password: update_password rotates the
      // token, so the old passwordless authToken is no longer valid and the
      // dashboard's auth guard would otherwise bounce the user to /signin.
      const { authToken } = await request({
        method: "POST",
        endpoint: "auth/login",
        body: { email, password: pw },
      });
      localStorage.setItem("authToken", authToken);

      const data = await request({
        method: "GET",
        endpoint: "auth/me",
        headers: { Authorization: `Bearer ${authToken}` },
      });
      localStorage.setItem("user", JSON.stringify(data));
      window.dispatchEvent(new Event("auth:user-changed"));

      // Signal the dashboard to auto-open the insight view for this first visit.
      localStorage.setItem("openInsight", "1");
      window.location.href = "/dashboard";
    } catch (e) {
      errorSwal(e?.message);
      setSettingPassword(false);
    }
  };

  /* ----- Render the active slide ----- */
  const renderSlide = () => {
    // The in-flight spinner is replaced by the animated `progress` slide, which
    // is shown as its own step while submit_onboarding runs.
    // if (processing) {
    //   return (
    //     <ProgressSlide
    //       heading="Creating your insight…"
    //       subtitle="We're mapping your relationship and preparing your free teaser. This only takes a moment."
    //       spinner
    //     />
    //   );
    // }

    switch (key) {
      case "relationship":
        // First slide — no back button.
        return (
          <RelationshipSlide
            results={results}
            setResults={setResults}
            slideRef={slideRef}
            onNext={goNext}
          />
        );
      case "story2":
        return <Story2Slide onBack={goBack} onNext={goNext} />;
      case "map":
        return <MapSlide onBack={goBack} onNext={goNext} />;
      case "names":
        return (
          <NamesSlide
            slideRef={slideRef}
            formData={results}
            isParent={isParent}
            onBack={goBack}
            onNext={goNext}
          />
        );
      case "birthdays":
        return (
          <BirthdaysSlide
            slideRef={slideRef}
            formData={results}
            isParent={isParent}
            onBack={goBack}
            onNext={goNext}
          />
        );
      case "confirm":
        return (
          <DataConfirmationStep
            values={results}
            isParent={isParent}
            onBack={goBack}
            onContinue={goNext}
            onEditParent={() => setStep(idx("names"))}
            onEditChild={() => setStep(idx("birthdays"))}
          />
        );
      case "gentleQuestions":
        return <GentleQuestionsSlide onBack={goBack} onNext={goNext} />;
      case "q2":
        return (
          <QuestionSlide
            Component={OnboardingQuestion2}
            slideRef={slideRef}
            formData={results}
            isParent={isParent}
            onBack={goBack}
            onNext={goNext}
          />
        );
      case "q3":
        return (
          <QuestionSlide
            Component={OnboardingQuestion3}
            slideRef={slideRef}
            formData={results}
            isParent={isParent}
            onBack={goBack}
            onNext={goNext}
          />
        );
      case "q4":
        return (
          <QuestionSlide
            Component={OnboardingQuestion4}
            slideRef={slideRef}
            formData={results}
            isParent={isParent}
            onBack={goBack}
            onNext={goNext}
          />
        );
      case "q5":
        return (
          <QuestionSlide
            Component={OnboardingQuestion5}
            slideRef={slideRef}
            formData={results}
            isParent={isParent}
            onBack={goBack}
            onNext={goNext}
          />
        );
      case "personal":
        return (
          <PersonalSlide
            slideRef={slideRef}
            formData={results}
            isParent={isParent}
            onBack={goBack}
            onNext={goNext}
          />
        );
      case "email":
        return (
          <EmailSlide
            email={email}
            setEmail={setEmail}
            onSubmit={submitAndFetchTeaser}
            processing={false}
            onBack={goBack}
          />
        );
      case "progress":
        return (
          <ProgressSlide
            ready={!!teaser}
            onComplete={() => {
              setStep(idx("teaser"));
              scrollTop();
            }}
          />
        );
      case "teaser":
        return (
          <TeaserSlide
            teaser={teaser}
            onUnlock={() => {
              setStep(idx("buy"));
              scrollTop();
            }}
          />
        );
      case "buy":
        return (
          <BuySlide
            onBuy={startCheckout}
            checkingOut={checkingOut}
            onBack={() => setStep(idx("teaser"))}
          />
        );
      case "afterPurchase":
        return (
          <AfterPurchaseSlide
            password={password}
            setPassword={setPassword}
            onSubmit={submitPassword}
            settingPassword={settingPassword}
          />
        );
      default:
        return null;
    }
  };

  return (
    <>
      <NavbarOnboarding />
      <div className={`signup-flow-patch ${SF.page}`} onSubmit={(e) => e.preventDefault()}>
        {renderSlide()}
      </div>
      <DashboardFooter />
    </>
  );
};

export default App;
